apiVersion: apps/v1
kind: Deployment
metadata:
  name: intelligent-train
  labels:
    app: intelligent-train
spec:
  replicas: 1
  selector:
    matchLabels:
      app: intelligent-train
  template:
    metadata:
      labels:
        app: intelligent-train
    spec:
      runtimeClassName: gpu-enabled-class
      containers:
      - name: intelligent-train
        image: quay.io/mregan/intelligent-train-app-arm64:latest